### ISSUE TITLE
'Conversation Signature' and 'No response was returned' error

### ISSUE THREAD

**Issue by DanielJara38** [vsakkas/sydney.py#44] opened 2023-08-25 03:06 UTC
Hey there! Firstly I just wanted to thank you for creating this package. It has helped me create a lot of cool things :)

I am getting the same issue, this hadn't happened before, but today I run the code and I got this:

![image](https://github.com/vsakkas/sydney.py/assets/56051663/b081c046-438f-44e0-b1c9-81f24be11900)
![image](https://github.com/vsakkas/sydney.py/assets/56051663/4ff9c2bf-f827-432e-aa1f-50fa615fe6e9)

I know that everything is right because I have been running the same code for a while now, so the _U cookie is correct I am sure of that. 

Could you point me on what could be the issue? Maybe they already patched it?

Thanks!

**Comment by vsakkas** [comment] 2023-08-26 15:22
Hi, this is a duplicate of this [issue](https://github.com/vsakkas/sydney.py/issues/43), so I will close this one. Thank you for taking the time to share your issue!

**Closed by vsakkas** 2023-08-26 15:22 UTC
