### ISSUE TITLE
Image query is not working 

### ISSUE THREAD

**Issue by robinai1212** [vsakkas/sydney.py#118] opened 2023-11-23 21:30 UTC
Please brother 🙏

**Comment by vsakkas** [comment] 2023-11-24 07:37
Hi @robinai1212 

Can you provide more information on what error you're getting? I can't seem to be able to reproduce such issue. Btw, if you're still using the _U cookie, keep in mind that it has been replaced and the README has been updated with new instructions!

**Comment by robinai1212** [comment] 2023-11-24 10:53
File "c:\Users\robin\Music\Playlists\AI Jarvis Using Python Tut\sydney.py", line 286, in _upload_attachment
    raise ImageUploadException(
exceptions.ImageUploadException: Failed to upload image, Copilot rejected uploading it
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019E5C202A90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000019E5C27E040>, 17450.718)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000019E5C276490>


import asyncio
from sydney import SydneyClient
from Body.Speak import Speak
import nest_asyncio

nest_asyncio.apply()

async def main() -> None:
    async with SydneyClient() as sydney:
       response = await sydney.ask("What does this picture show?", attachment="img.jpg")
       print(response)


if __name__ == "__main__":
    asyncio.run(main())

**Comment by robinai1212** [comment] 2023-11-24 10:54
Help please

File "c:\Users\robin\Music\Playlists\AI Jarvis Using Python Tut\sydney.py", line 286, in _upload_attachment
raise ImageUploadException(
exceptions.ImageUploadException: Failed to upload image, Copilot rejected uploading it
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000019E5C202A90>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000019E5C27E040>, 17450.718)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000019E5C276490>

import asyncio
from sydney import SydneyClient
from Body.Speak import Speak
import nest_asyncio

nest_asyncio.apply()

async def main() -> None:
async with SydneyClient() as sydney:
response = await sydney.ask("What does this picture show?", attachment="img.jpg")
print(response)

if name == "main":
asyncio.run(main())

**Comment by vsakkas** [comment] 2023-11-24 14:13
Hi @robinai1212

To be clear, is "img.jpg" a URL or a file path in your case? It should be a URL

**Comment by vsakkas** [comment] 2023-11-26 18:06
Update: I can see indeed that very often Bing Chat does not return a response when using this feature, I will try to investigate a bit more to see what's the root cause.

@robinai1212

**Comment by vsakkas** [comment] 2023-11-26 20:30
Latest version contains a fix for this, will close this one for now

**Closed by vsakkas** 2023-11-26 20:30 UTC
Labels: bug, needs information
