### ISSUE TITLE
conversationSignature key error

### ISSUE THREAD

**Issue by jacobgelling** [vsakkas/sydney.py#51] opened 2023-10-05 07:33 UTC
Perhaps Bing Chat operates differently in different regions or there has been a update to how this is handled, but for me the ```conversationSignature``` is assigned in the conversation response headers as ```X-Sydney-Conversationsignature``` and ```X-Sydney-Encryptedconversationsignature```, not in the response body. Also there is no ```throttling``` key in the chathub response.

```X-Sydney-Conversationsignature``` is used in exactly the same way as conversationSignature is currently handled.

```X-Sydney-Encryptedconversationsignature``` is encoded for use as a GET parameter and included in all requests to ```BING_CHATHUB_URL```, so the URL used should be ```BING_CHATHUB_URL + f"?sec_access_token={urllib.parse.quote(X-Sydney-Encryptedconversationsignature)}"```

Without all these changes, Sydney.py does not run for me.

**Comment by vsakkas** [comment] 2023-10-05 11:33
Hi @jacobgelling Thanks for opening this issue and the PR!

Indeed, looks like there was some recent change, so the conversation signature is no longer included in the response body. I will have a look at your PR as soon as I have time!

**Comment by BlackDicky** [comment] 2023-10-05 23:30
I'm also getting this error: ```
"File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sydney/sydney.py", line 363, in start_conversation
    self.conversation_signature = response_dict["conversationSignature"]
                                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'"
``` how can I fix it?

**Comment by BlackDicky** [comment] 2023-10-05 23:31
I'm also getting this error: `File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sydney/sydney.py", line 363, in start_conversation
    self.conversation_signature = response_dict["conversationSignature"]
                                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'" `

**Comment by vsakkas** [comment] 2023-10-06 06:57
Hi @BlackDicky There is a [PR](https://github.com/vsakkas/sydney.py/pull/52) which will soon get merged. Once merged, I will release a new build with the fix and you update to the latest version.
The issue is that the API for using Bing Chat has changed in a non backwards compatible way.

**Comment by vsakkas** [comment] 2023-10-06 07:28
Version `v0.15.0` with a fix has been released! Closing this issue for now

**Closed by vsakkas** 2023-10-06 07:28 UTC
Labels: bug
